version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./application/events.db:/application/events.db
    depends_on:
      - redis
      - celery

  celery:
    build: .
    command: celery -A application.celery worker --loglevel=info
    volumes:
      - ./application/events.db:/application/events.db
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A application.celery beat --loglevel=info
    volumes:
      - ./application/events.db:/application/events.db
    depends_on:
      - celery
      - redis

  redis:
    image: "redis:alpine"
